#!/usr/bin/python3
"""factorize as many numbers as possible
 into a product of two smaller numbers."""
from sys import argv


def factorize(v):
    """"print a simple descomposition of an integer > 1"""
    f = 2

    if v < 2:
        return
    if v % f == 0:
        print("{:.0f}={:.0f}*{:.0f}".format(v, v / f, f))
        return
    f = 3
    while f * f <= v:
        if f > 1000:
            print("{:.0f}={:.0f}*{:.0f}".format(v, v ** 0.5, v ** 0.5))
            return
        f += 2
    print("{:.0f}={:.0f}*{:.0f}".format(v, v / f , f))


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            v = int(line.split('\n')[0])
            factorize(v)
            line = file.readline()
except:
    exit()
