#!/usr/bin/python3
"""factorize as many numbers as possible
 into a product of two smaller numbers."""
from sys import argv
from math import sqrt # import sqrt function


def factorize(v):
    """"print a simple descomposition of an integer > 1"""
    x = 2

    if v < 2:
        return
    if v % x == 0:
        print("{:.0f}={:.0f}*{:.0f}".format(v, v / x, x))
        return
    limit = int(sqrt(v)) # set the limit to the square root of v
    for factor in range(3, limit + 1, 2): # use for loop with range function
        if v % factor == 0:
            print("{:.0f}={:.0f}*{:.0f}".format(v, v / factor , factor))
            break # break the loop if a factor is found
    else: # use break-else construct
        # if no factors are found, print prime number
        print("{:.0f}={:.0f}*{:.0f}".format(v, 1 , v))


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file: # use with statement to handle file opening and closing
        for line in file: # iterate over the lines in the file
            v = int(line.strip()) # strip the newline character from the line
            factorize(v)
except:
    pass
