#!/usr/bin/python3
"""factorize as many numbers as possible
 into a product of two smaller numbers."""
from sys import argv


def factorize(v):
    """"print a simple descomposition of an integer > 1"""
    x = 2

    if v < 2:
        return
    if v % x == 0:
        print("{:.0f}={:.0f}*{:.0f}".format(v, v / x, x))
        return
    f = 3
    if v % f == 0:
        print("{:.0f}={:.0f}*{:.0f}".format(v, v / f, f))
        return
    while f < v / 2:
        if f > 2000:
            print("{:.0f}={:.0f}*{:.0f}".format(v, v ** 0.5, v ** 0.5))
            return
        if v % f == 0: 
            print("{:.0f}={:.0f}*{:.0f}".format(v, v / f , f))
            break
        f += 2 


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            v = int(line.split('\n')[0])
            factorize(v)
            line = file.readline()
except:
    pass
